version: 2
jobs:
  terraform_apply:
    working_directory: ~/tmp
    docker:
            - image: hashicorp/terraform:light

    steps:
      - checkout
      - run:
          name: terraform apply
          command: |
            terraform taint aws_instance.ubuntu
            terraform apply 

workflows:
  version: 2
  terraform:
    jobs:
      - terraform_apply