version: '2.1'
orbs:
  terraform: circleci/terraform@2.0.1
jobs:
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - checkout
      - run:
          command:|
          terraform taint aws_instance.ubuntu
          terraform apply
workflows:
  single-job-lifecycle:
    jobs:
      - single-job-lifecycle