version: 2
jobs:
  terraform_taint:
    working_directory: ~/tmp
    docker:
            - image: hashicorp/terraform:light
            - image: ubuntu:16.04

    steps:
      - checkout
      - run:
          name: terraform taint 
          command: |
            terraform taint aws_instance.ubuntu
            terraform apply
    

workflows:
  version: 2
  terraform:
    jobs:
      - terraform_taint
      