version: '2.1'
orbs:
  terraform: circleci/terraform@2.0.1
jobs:
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - run:
          command: |
           terraform taint
    working_directory: .
workflows:
  single-job-lifecycle:
    jobs:
      - single-job-lifecycle
          

